// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUT2/bPgz9KgV/v6Nned2l0K0biiHANhRrb0UxaA5rq7UlVaSXBYG/+0DZSZwmXTc0",
	"O1mW+Mj3+G8FpW+Dd+iYQK+Ayhpbk45XtnLWfcXHDonlAn+aNjSYjq2xDejxm0EwRAsf56C3xz6DEH3A",
	"yBZpAloBLwOCBuJoXZXsNvC9xz6DiI+djTgHfbMf8DZbI/z3eyxZ3AnzLvwZc2daAafPq3UMzo4i8Cmh",
	"QzqvDT08kceW5TB+96iPzy+RGMz2Q4qddXdePJTesSlTesccXow0+gzmSGW0ga13k4cMGluiI5yAzoMp",
	"azw5zQvIoItSmpo5kFZqsVjkJj3nPlZqxJL6NPtw8eXq4s1pXuQ1t40EXOseQ52cX84ggx8YaaDwNi/y",
	"Qgx9QGeCBQ3v0pWkmOuUHNUuv7Ghh/RTYZImyTMiYyY98RH58/I6mUjCKHghJHanRbFOCrqENCE0tkxY",
	"dU9CYj1dcrKMbQL+H/EONPyntnOoxiFUqb79pgomRrMcirCb39pXKPd9BorS1Irn4OmAhEtPPEw2DDVH",
	"4vd+vvwr9r8jvbs2DrClafSh4zh22B/O6C52bTFV24WX1XbhH6rdrppn1G6iv1LtpjmfF7ttzuNrHdpx",
	"X6LQOoLAPgPCKCML+mY12QVaqcaXpqk9sT4rzgroZTWZajDcddkRxu1aT3/9bf8rAAD//0YJyrLnBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
