// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package oapi

// Todo defines model for todo.
type Todo struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// TodoJSONBody defines parameters for Todo.
type TodoJSONBody Todo

// TodoJSONRequestBody defines body for Todo for application/json ContentType.
type TodoJSONRequestBody TodoJSONBody

