// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package oapi

// Signin defines model for signin.
type Signin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Signup defines model for signup.
type Signup struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostSigninJSONBody defines parameters for PostSignin.
type PostSigninJSONBody Signin

// PostSignupJSONBody defines parameters for PostSignup.
type PostSignupJSONBody Signup

// PostSigninJSONRequestBody defines body for PostSignin for application/json ContentType.
type PostSigninJSONRequestBody PostSigninJSONBody

// PostSignupJSONRequestBody defines body for PostSignup for application/json ContentType.
type PostSignupJSONRequestBody PostSignupJSONBody

