// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCreateTasks holds the string denoting the create_tasks edge name in mutations.
	EdgeCreateTasks = "create_tasks"
	// Table holds the table name of the user in the database.
	Table = "users"
	// CreateTasksTable is the table that holds the create_tasks relation/edge.
	CreateTasksTable = "tasks"
	// CreateTasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	CreateTasksInverseTable = "tasks"
	// CreateTasksColumn is the table column denoting the create_tasks relation/edge.
	CreateTasksColumn = "user_create_tasks"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
